CREATE DATABASE PASTELERIA;
USE PASTELERIA;

CREATE TABLE PRODUCTO(
	ID_PRODUCTO BIGINT NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(30) NOT NULL,
    DESCRIPCION VARCHAR(50),
    PRECIO DECIMAL(10,2) NOT NULL,
    CATEGORIA VARCHAR(15) NOT NULL, 
    STOCK INTEGER NOT NULL,
    CONSTRAINT PK_PRODUCTO PRIMARY KEY(ID_PRODUCTO)
);

CREATE TABLE INGREDIENTE(
	ID_INGREDIENTE BIGINT NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(100) NOT NULL,
    PRECIO DECIMAL(10,2) NOT NULL,
    STOCK INT NOT NULL,
    FABRICANTE VARCHAR(100) NOT NULL,
    CONSTRAINT PK_INGREDIENTE PRIMARY KEY(ID_INGREDIENTE)
);

CREATE TABLE PRODUCTO_INGREDIENTE(
	ID_PRODUCTO_INGREDIENTE BIGINT NOT NULL AUTO_INCREMENT,
	ID_PRODUCTO BIGINT NOT NULL,
    ID_INGREDIENTE BIGINT NOT NULL,
    CONSTRAINT PK_PRODUCTO_INGREDIENTE PRIMARY KEY(ID_PRODUCTO_INGREDIENTE),
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO),
    FOREIGN KEY (ID_INGREDIENTE) REFERENCES INGREDIENTE(ID_INGREDIENTE)
);

CREATE TABLE CLIENTE (
    ID_CLIENTE BIGINT NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(100) NOT NULL,
    APELLIDO VARCHAR(100) NOT NULL,
    DIRECCION TEXT NOT NULL,
    TELEFONO VARCHAR(15) UNIQUE NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    USUARIO VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR(50) NOT NULL,
    CONSTRAINT PK_CLIENTE PRIMARY KEY(ID_CLIENTE)
);

CREATE TABLE PEDIDO(
	ID_PEDIDO BIGINT NOT NULL AUTO_INCREMENT,
    ID_CLIENTE BIGINT,
    FECHA DATETIME NOT NULL,
    PRECIO_TOTAL DECIMAL (10,2) NOT NULL,
    OBSERVACIONES VARCHAR(50) NOT NULL,
    ESTADO VARCHAR(50) NOT NULL,
    CONSTRAINT PK_PEDIDO PRIMARY KEY (ID_PEDIDO),
    CONSTRAINT FK_PEDIDO_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
);

CREATE TABLE PEDIDO_PRODUCTO(
	ID_PEDIDO BIGINT,
    ID_PRODUCTO BIGINT,
    CANTIDAD INTEGER NOT NULL,
    CONSTRAINT PK_PEDIDO_PRODUCTO PRIMARY KEY (ID_PEDIDO,ID_PRODUCTO),
    FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO(ID_PEDIDO),
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO)
);

CREATE TABLE EMPLEADO(
	ID_EMPLEADO BIGINT NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(100) NOT NULL,
    APELLIDO VARCHAR(100) NOT NULL,
    TELEFONO VARCHAR(15) NOT NULL,
    FECHACONTRATACION DATE NOT NULL,
    ROL VARCHAR(50) NOT NULL,
	USUARIO VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR(50) NOT NULL UNIQUE,
    CONSTRAINT PK_EMPLEADO PRIMARY KEY (ID_EMPLEADO)
);

CREATE TABLE REGISTRO_EMPLEADO(
	ID_REGISTRO BIGINT NOT NULL AUTO_INCREMENT,
    ID_EMPLEADO BIGINT NOT NULL,
    HORA_ENTRADA DATETIME NOT NULL,
    HORA_SALIDA DATETIME NULL,
    CONSTRAINT PK_REGISTRO_EMPLEADO PRIMARY KEY (ID_REGISTRO),
    CONSTRAINT FK_REGISTRO_EMPLEADO FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO(ID_EMPLEADO)
);

select * from cliente;
select * from empleado;

DROP DATABASE PASTELERIA;