CREATE DATABASE TIENDA_INFORMATICA;
USE TIENDA_INFORMATICA;

CREATE TABLE FABRICANTE (
     ID_FABRICANTE  BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Identificador del Fabricante', 
     NOMBRE VARCHAR(30) COMMENT 'Nombre del fabricante', 
     CONSTRAINT PK_FABRICANTE PRIMARY KEY (ID_FABRICANTE)
);

CREATE TABLE ARTICULO (
     ID_ARTICULO  BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Identificador del Articulo', 
     NOMBRE VARCHAR(30) COMMENT 'Nombre del artículo', 
     PRECIO INT COMMENT 'Precio del artículo', 
     ID_FABRICANTE BIGINT COMMENT 'Identificador del Fabricante',
     CONSTRAINT PK_ARTICULO PRIMARY KEY (ID_ARTICULO),
     CONSTRAINT FK_ARTICULO_FABRICANTE  FOREIGN KEY (ID_FABRICANTE) REFERENCES FABRICANTE(ID_FABRICANTE)
);

INSERT INTO FABRICANTE (ID_FABRICANTE, NOMBRE)  VALUES (1 , 'Kingston'); 
INSERT INTO FABRICANTE (ID_FABRICANTE, NOMBRE)  VALUES (2 , 'Adata'); 
INSERT INTO FABRICANTE (ID_FABRICANTE, NOMBRE)  VALUES (3 , 'Logitech'); 
INSERT INTO FABRICANTE (ID_FABRICANTE, NOMBRE)  VALUES (4 , 'Lexar'); 
INSERT INTO FABRICANTE (ID_FABRICANTE, NOMBRE)  VALUES (5 , 'Seagate'); 
 
INSERT INTO ARTICULO (ID_ARTICULO, NOMBRE, PRECIO, ID_FABRICANTE)  VALUES (1 , 'Teclado', 100, 3); 
INSERT INTO ARTICULO (ID_ARTICULO, NOMBRE, PRECIO, ID_FABRICANTE)  VALUES (2 , 'Disco duro 300Gb', 500, 5);
INSERT INTO ARTICULO (ID_ARTICULO, NOMBRE, PRECIO, ID_FABRICANTE)  VALUES (3 , 'Mouse', 80, 3);
INSERT INTO ARTICULO (ID_ARTICULO, NOMBRE, PRECIO, ID_FABRICANTE)  VALUES (4 , 'Memoria USB', 140, 4);
INSERT INTO ARTICULO (ID_ARTICULO, NOMBRE, PRECIO, ID_FABRICANTE)  VALUES (5 , 'Memoria RAM', 290, 1);
INSERT INTO ARTICULO (ID_ARTICULO, NOMBRE, PRECIO, ID_FABRICANTE)  VALUES (6 , 'Disco duro extraíble 250Gb', 650, 5);
INSERT INTO ARTICULO (ID_ARTICULO, NOMBRE, PRECIO, ID_FABRICANTE)  VALUES (7 , 'Memoria USB', 279, 1);
INSERT INTO ARTICULO (ID_ARTICULO, NOMBRE, PRECIO, ID_FABRICANTE)  VALUES (8 , 'DVD Rom', 450, 2);
INSERT INTO ARTICULO (ID_ARTICULO, NOMBRE, PRECIO, ID_FABRICANTE)  VALUES (9 , 'CD ROM', 200, 2);
INSERT INTO ARTICULO (ID_ARTICULO, NOMBRE, PRECIO, ID_FABRICANTE)  VALUES (10, 'Tarjeta de red', 180, 3);