CREATE DATABASE EMPRESA;
USE EMPRESA;

CREATE TABLE DEPARTAMENTO (
	ID_DEPARTAMENTO INT NOT NULL COMMENT 'Identificador de la tabla departamento',
    NOMBRE VARCHAR(20) NOT NULL COMMENT 'Nombre de la tabla departamento',
    NUM_EMPLEADOS INT NOT NULL  COMMENT 'Numero de empleados',
    FECHA_INICIO DATE NULL COMMENT 'Fecha de inicio de la tabla departamento',
    DIRECTOR VARCHAR(30) NOT NULL COMMENT 'Director del departamento',
    CONSTRAINT PK_DEPARTAMENTO PRIMARY KEY (ID_DEPARTAMENTO)
);

CREATE TABLE PROYECTO (
	ID_CODIGO INT NOT NULL COMMENT 'Identificador de la tabla proyecto',
    NOMBRE VARCHAR(20) NOT NULL COMMENT 'Nombre de la tabla proyecto',
    LOCALIDAD VARCHAR(40) NOT NULL COMMENT 'Localidad del proyecto',
    ID_DEPARTAMENTO INT NOT NULL,
    CONSTRAINT PK_PROYECTO PRIMARY KEY (ID_CODIGO),
    CONSTRAINT FK_DEPARTAMENTO FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTO (ID_DEPARTAMENTO)
);

CREATE TABLE EMPLEADO (
	ID_NUSS INT NOT NULL COMMENT 'Identificador de la tabla empleado',
    NOMBRE VARCHAR(20) NOT NULL COMMENT 'Nombre del empleado',
    SEXO VARCHAR(10) NOT NULL COMMENT 'Genero del empleado',
    DIRECCION VARCHAR(30) NOT NULL COMMENT 'Direccion del empleado',
    FECHA_NAC DATE NOT NULL COMMENT 'Fecha de nacimiento del empleado',
    SALARIO DOUBLE NOT NULL COMMENT 'Salario del empleado',
    ID_DEPARTAMENTO INT NOT NULL,
    CONSTRAINT PK_EMPLEADO PRIMARY KEY (ID_NUSS),
    CONSTRAINT FK_DEPARTAMENTO1 FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTO (ID_DEPARTAMENTO)
);

CREATE TABLE TRABAJA (
	NUM_HORAS INT NOT NULL COMMENT 'Numero de horas',
    ID_NUSS INT NOT NULL COMMENT 'Identificador de la tabla empleado',
    ID_CODIGO INT NOT NULL COMMENT 'Identificador de la tabla proyecto',
    CONSTRAINT FK_EMPLEADO FOREIGN KEY (ID_NUSS) REFERENCES EMPLEADO (ID_NUSS),
    CONSTRAINT FK_PROYECTO FOREIGN KEY (ID_CODIGO) REFERENCES PROYECTO (ID_CODIGO)
);
