/*Punto 1*/
CREATE DATABASE TIENDA;

USE TIENDA;

CREATE TABLE FABRICANTE (
ID_FABRICANTE  INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador del Fabricante',       
NOMBRE VARCHAR(30) NOT NULL COMMENT 'Nombre del fabricante',       
CIUDAD VARCHAR(100) NOT NULL COMMENT 'Nombre de la ciudad del fabricante',      
CONSTRAINT PK_FABRICANTE PRIMARY KEY (ID_FABRICANTE) 
) COMMENT 'Datos de los fabricantes';

CREATE TABLE ARTICULO (      
ID_ARTICULO  INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador del Articulo',       
NOMBRE VARCHAR(30) COMMENT 'Nombre del artículo',       
PRECIO INT COMMENT 'Precio del artículo',       
ID_FABRICANTE INT COMMENT 'Identificador del Fabricante',      
CONSTRAINT PK_ARTICULO PRIMARY KEY (ID_ARTICULO),      
CONSTRAINT FK_ARTICULO_FABRICANTE  FOREIGN KEY (ID_FABRICANTE) REFERENCES FABRICANTE(ID_FABRICANTE) 
) COMMENT 'Datos de los articulos de los distintos fabricantes';


/*Punto 2*/

DESCRIBE ARTICULO;

/*Punto 3*/

/*INSERT PARA LA TABLA FABRICANTE*/
INSERT INTO FABRICANTE(NOMBRE, CIUDAD)  VALUES('Kingston','Leon');
INSERT INTO FABRICANTE(NOMBRE, CIUDAD)  VALUES('Adata', 'Madrid');
INSERT INTO FABRICANTE(NOMBRE, CIUDAD)  VALUES('Logitech','Toledo');
INSERT INTO FABRICANTE(NOMBRE, CIUDAD)  VALUES('Lexar','Zamora');
INSERT INTO FABRICANTE(NOMBRE, CIUDAD)  VALUES('Seagate','Valladolid');

/*INSERT PARA LA TABLA ARTICULO*/
INSERT INTO ARTICULO (NOMBRE, PRECIO, ID_FABRICANTE)  VALUES ( 'Teclado', 100, 3);
INSERT INTO ARTICULO (NOMBRE, PRECIO, ID_FABRICANTE)  VALUES ( 'Disco duro 300Gb', 500, 5);
INSERT INTO ARTICULO (NOMBRE, PRECIO, ID_FABRICANTE)  VALUES ( 'Mouse', 80, 3);
INSERT INTO ARTICULO (NOMBRE, PRECIO, ID_FABRICANTE)  VALUES ( 'Memoria USB', 140, 4);
INSERT INTO ARTICULO (NOMBRE, PRECIO, ID_FABRICANTE)  VALUES ( 'Memoria RAM', 290, 1);
INSERT INTO ARTICULO (NOMBRE, PRECIO, ID_FABRICANTE)  VALUES ( 'Disco duro extraíble 250Gb', 650, 5);
INSERT INTO ARTICULO (NOMBRE, PRECIO, ID_FABRICANTE)  VALUES ( 'Memoria USB', 279, 1);
INSERT INTO ARTICULO (NOMBRE, PRECIO, ID_FABRICANTE)  VALUES ( 'DVD Rom', 450, 2);
INSERT INTO ARTICULO (NOMBRE, PRECIO, ID_FABRICANTE)  VALUES ( 'CD ROM', 200, 2);
INSERT INTO ARTICULO (NOMBRE, PRECIO, ID_FABRICANTE)  VALUES ( 'Tarjeta de red', 180, 3);

/*Punto 4*/
ALTER TABLE FABRICANTE ADD COLUMN NUM_TFNO INT NOT NULL COMMENT 'Numero de telefono del fabricante';

/*Punto 5*/
UPDATE ARTICULO
SET NOMBRE = 'Nueva tarjeta de red'
WHERE PRECIO = 180;

/*Punto 6*/
UPDATE FABRICANTE
SET NUM_TFNO = 123456789
WHERE CIUDAD = 'Leon';

UPDATE FABRICANTE
SET NUM_TFNO = 78946513
WHERE CIUDAD = 'Madrid';

UPDATE FABRICANTE
SET NUM_TFNO = 741852963
WHERE CIUDAD = 'Toledo';

/*Punto 7*/
UPDATE ARTICULO
SET PRECIO = PRECIO + 120
WHERE NOMBRE = 'Teclado';

/*Punto 8*/
UPDATE ARTICULO
SET PRECIO = 0
WHERE ID_FABRICANTE = 3;

/*Punto 9*/
UPDATE ARTICULO
SET PRECIO = PRECIO - 26
WHERE ID_FABRICANTE = 4 AND (NOMBRE = 'Memoria USB' OR NOMBRE = 'Memoria RAM');