
-- -----------------------------------------------------
-- Table TIPO_INMUEBLE
-- -----------------------------------------------------
CREATE TABLE TIPO_INMUEBLE (
  CODIGO_TIPO_INMUEBLE VARCHAR2(10) NOT NULL,
  DESCRIPCION VARCHAR2(200) NOT NULL,
  CONSTRAINT PK_TIPO_INMUEBLE PRIMARY KEY (CODIGO_TIPO_INMUEBLE)
);

COMMENT ON TABLE TIPO_INMUEBLE IS 'Tabla tipo inmueble';
COMMENT ON COLUMN TIPO_INMUEBLE.CODIGO_TIPO_INMUEBLE IS 'Tipo de inmueble';
COMMENT ON COLUMN TIPO_INMUEBLE.DESCRIPCION IS 'DescripciÃ³n del tipo de inmueble';

-- -----------------------------------------------------
-- Table INMUEBLE
-- -----------------------------------------------------
CREATE TABLE INMUEBLE (
  ID_INMUEBLE NUMBER NOT NULL,
  DIRECCION VARCHAR2(300) NOT NULL,
  POBLACION VARCHAR2(100) NOT NULL,
  CODIGO_POSTAL NUMBER,
  PRECIO_VENTA NUMBER(12,2),
  PRECIO_ALQUILER NUMBER(12,2),
  FECHA_ULTIMO_MOV DATE,
  OBSERVACIONES VARCHAR2(300),
  CODIGO_TIPO_INMUEBLE VARCHAR2(10) NOT NULL,
  CONSTRAINT PK_INMUEBLE PRIMARY KEY (ID_INMUEBLE),
  CONSTRAINT FK_INMUEBLE_TIPO_INMUEBLE FOREIGN KEY (CODIGO_TIPO_INMUEBLE) REFERENCES TIPO_INMUEBLE(CODIGO_TIPO_INMUEBLE)
);

COMMENT ON TABLE INMUEBLE IS 'Tabla tipo inmueble';
COMMENT ON COLUMN INMUEBLE.ID_INMUEBLE IS 'Identificador del inmueble';
COMMENT ON COLUMN INMUEBLE.DIRECCION IS 'DirecciÃ³n del inmueble';
COMMENT ON COLUMN INMUEBLE.POBLACION IS 'PoblaciÃ³n del inmueble';
COMMENT ON COLUMN INMUEBLE.CODIGO_POSTAL IS 'CÃ³digo Postal del inmueble';
COMMENT ON COLUMN INMUEBLE.PRECIO_VENTA IS 'Precio de venta inicial del inmueble';
COMMENT ON COLUMN INMUEBLE.PRECIO_ALQUILER IS 'Precio de alquiler inicial del inmueble';
COMMENT ON COLUMN INMUEBLE.FECHA_ULTIMO_MOV IS 'Fecha del Ãºltimo movimiento del inmueble';
COMMENT ON COLUMN INMUEBLE.OBSERVACIONES IS 'Observaciones del inmueble';
COMMENT ON COLUMN INMUEBLE.CODIGO_TIPO_INMUEBLE IS 'Tipo de inmueble';

-- -----------------------------------------------------
-- Table ESTADO
-- -----------------------------------------------------
CREATE TABLE ESTADO (
  CODIGO_ESTADO VARCHAR2(10) NOT NULL,
  DESCRIPCION VARCHAR2(200),
  CONSTRAINT PK_ESTADO PRIMARY KEY (CODIGO_ESTADO)
);

COMMENT ON TABLE ESTADO IS 'Tabla estado';
COMMENT ON COLUMN ESTADO.CODIGO_ESTADO IS 'Estado del inmueble';
COMMENT ON COLUMN ESTADO.DESCRIPCION IS 'DescripciÃ³n del estado del inmueble';


-- -----------------------------------------------------
-- Table TIPO_MOVIMIENTO
-- -----------------------------------------------------
CREATE TABLE TIPO_MOVIMIENTO (
  CODIGO_TIPO_MOVIMIENTO VARCHAR2(10) NOT NULL,
  DESCRIPCION VARCHAR2(200) NOT NULL,
  CONSTRAINT PK_TIPO_MOVIMIENTO PRIMARY KEY (CODIGO_TIPO_MOVIMIENTO)
);

COMMENT ON TABLE TIPO_MOVIMIENTO IS 'Tabla estado';
COMMENT ON COLUMN TIPO_MOVIMIENTO.CODIGO_TIPO_MOVIMIENTO IS 'Tipo de movimiento del inmueble';
COMMENT ON COLUMN TIPO_MOVIMIENTO.DESCRIPCION IS 'DescripciÃ³n del tipo de movimiento del inmueble';

-- -----------------------------------------------------
-- Table CLIENTE
-- -----------------------------------------------------
CREATE TABLE CLIENTE (
  DNI VARCHAR2(9) NOT NULL,
  DIRECCION VARCHAR2(300),
  POBLACION VARCHAR2(100),
  EMAIL VARCHAR2(100),
  TELEFONO VARCHAR2(15) NOT NULL,
  NOMBRE VARCHAR2(50) NOT NULL,
  APELLIDOS VARCHAR2(150) NOT NULL,
  CONSTRAINT PK_CLIENTE PRIMARY KEY (DNI)
);

COMMENT ON TABLE CLIENTE IS 'Tabla cliente';
COMMENT ON COLUMN CLIENTE.DNI IS 'DNI del cliente';
COMMENT ON COLUMN CLIENTE.DIRECCION IS 'DirecciÃ³n del cliente';
COMMENT ON COLUMN CLIENTE.POBLACION IS 'PoblaciÃ³n del cliente';
COMMENT ON COLUMN CLIENTE.EMAIL IS 'DirecciÃ³n de correo del cliente';
COMMENT ON COLUMN CLIENTE.TELEFONO IS 'Telefono del cliente';
COMMENT ON COLUMN CLIENTE.NOMBRE IS 'Nombre del cliente';
COMMENT ON COLUMN CLIENTE.APELLIDOS IS 'Apellidos del cliente';


-- -----------------------------------------------------
-- Table HORARIO
-- -----------------------------------------------------
CREATE TABLE HORARIO (
  CODIGO VARCHAR2(10) NOT NULL,
  DESCRIPCION VARCHAR2(200) NOT NULL,
  CONSTRAINT PK_HORARIO PRIMARY KEY (CODIGO)
);

COMMENT ON TABLE HORARIO IS 'Tabla horario';
COMMENT ON COLUMN HORARIO.CODIGO IS 'CÃ³digo del tipo de horario';
COMMENT ON COLUMN HORARIO.DESCRIPCION IS 'DescripciÃ³n del tipo de horario';

-- -----------------------------------------------------
-- Table AGENTE
-- -----------------------------------------------------
CREATE TABLE AGENTE (
  DNI VARCHAR2(9) NOT NULL,
  DIRECCION VARCHAR2(300),
  POBLACION VARCHAR2(100),
  EMAIL VARCHAR2(100),
  TELEFONO VARCHAR2(15) NOT NULL,
  NOMBRE VARCHAR2(50) NOT NULL,
  APELLIDOS VARCHAR2(150) NOT NULL,
  SALARIO_BASE NUMBER(12) NOT NULL,
  OBSERVACIONES VARCHAR2(300),
  HORARIO_CODIGO VARCHAR2(10) NOT NULL,
  CONSTRAINT PK_AGENTE PRIMARY KEY (DNI),
  CONSTRAINT FK_AGENTE_HORARIO FOREIGN KEY (HORARIO_CODIGO) REFERENCES HORARIO (CODIGO)
);

COMMENT ON TABLE AGENTE IS 'Tabla agente';
COMMENT ON COLUMN AGENTE.DNI IS 'DNI del Agente';
COMMENT ON COLUMN AGENTE.DIRECCION IS 'DirecciÃ³n del Agente';
COMMENT ON COLUMN AGENTE.POBLACION IS 'PoblaciÃ³n del Agente';
COMMENT ON COLUMN AGENTE.EMAIL IS 'DirecciÃ³n de correo electrÃ³nico del Agente';
COMMENT ON COLUMN AGENTE.TELEFONO IS 'Telefono del Agente';
COMMENT ON COLUMN AGENTE.NOMBRE IS 'Nombre del Agente';
COMMENT ON COLUMN AGENTE.APELLIDOS IS 'Apellidos del agente';
COMMENT ON COLUMN AGENTE.SALARIO_BASE IS 'Salario base del Agente';
COMMENT ON COLUMN AGENTE.OBSERVACIONES IS 'Observaciones del Agente';
COMMENT ON COLUMN AGENTE.HORARIO_CODIGO IS 'Horario del Agente' ;



-- -----------------------------------------------------
-- Table MOVIMIENTO
-- -----------------------------------------------------
CREATE TABLE MOVIMIENTO (
  ID_MOVIMIENTO NUMBER NOT NULL,
  FECHA_MOVIMIENTO DATE NOT NULL,
  PRECIO NUMBER(12,2) NOT NULL,
  ID_INMUEBLE NUMBER NOT NULL,
  CODIGO_TIPO_MOVIMIENTO VARCHAR2(10) NOT NULL,
  CLIENTE_DNI VARCHAR2(9) NOT NULL,
  AGENTE_DNI VARCHAR2(9) NOT NULL,
  CONSTRAINT PK_MOVIMIENTO PRIMARY KEY (ID_MOVIMIENTO),
  CONSTRAINT FK_MOVIMIENTO_ID_INMUEBLE FOREIGN KEY (ID_INMUEBLE) REFERENCES INMUEBLE (ID_INMUEBLE),
  CONSTRAINT FK_MOVIMIENTO_TIPO_MOVIMIENTO FOREIGN KEY (CODIGO_TIPO_MOVIMIENTO) REFERENCES TIPO_MOVIMIENTO (CODIGO_TIPO_MOVIMIENTO),
  CONSTRAINT FK_MOVIMIENTO_CLIENTE FOREIGN KEY (CLIENTE_DNI) REFERENCES CLIENTE (DNI),
  CONSTRAINT FK_MOVIMIENTO_AGENTE FOREIGN KEY (AGENTE_DNI) REFERENCES AGENTE (DNI)
);

COMMENT ON TABLE MOVIMIENTO IS 'Tabla Movimiento';
COMMENT ON COLUMN MOVIMIENTO.ID_MOVIMIENTO IS 'Identificador del Movimiento';
COMMENT ON COLUMN MOVIMIENTO.FECHA_MOVIMIENTO IS 'Fecha del Movimiento';
COMMENT ON COLUMN MOVIMIENTO.PRECIO IS 'Precio final del Movimiento';
COMMENT ON COLUMN MOVIMIENTO.ID_INMUEBLE IS 'Identificador del Inmueble sobre el que se realizÃ³ el alquiler/venta';
COMMENT ON COLUMN MOVIMIENTO.CODIGO_TIPO_MOVIMIENTO IS 'Tipo del Movimiento: alquiler/venta';
COMMENT ON COLUMN MOVIMIENTO.CLIENTE_DNI IS 'DNI del cliente que realizÃ³ el movimiento';
COMMENT ON COLUMN MOVIMIENTO.AGENTE_DNI IS 'DNI del agente que realizÃ³ el movimiento';

-- -----------------------------------------------------
-- Table INMUEBLE_ESTADO
-- -----------------------------------------------------
CREATE TABLE INMUEBLE_ESTADO (
  ID_INMUEBLE NUMBER NOT NULL,
  CODIGO_ESTADO VARCHAR2(10) NOT NULL,
  CONSTRAINT PK_INMUEBLE_ESTADO PRIMARY KEY (ID_INMUEBLE, CODIGO_ESTADO),
  CONSTRAINT FK_INMUEBLE_ESTADO_INMUEBLE FOREIGN KEY (ID_INMUEBLE) REFERENCES INMUEBLE (ID_INMUEBLE),
  CONSTRAINT FK_INMUEBLE_ESTADO_ESTADO FOREIGN KEY (CODIGO_ESTADO) REFERENCES ESTADO (CODIGO_ESTADO)
);

COMMENT ON TABLE INMUEBLE_ESTADO IS 'Tabla Inmueble estado';
COMMENT ON COLUMN INMUEBLE_ESTADO.ID_INMUEBLE IS 'Identificador del inmueble';
COMMENT ON COLUMN INMUEBLE_ESTADO.CODIGO_ESTADO IS 'Fecha del Movimiento';


-- -----------------------------------------------------
-- Table COMISION
-- -----------------------------------------------------
CREATE TABLE COMISION (
  ID_COMISION NUMBER NOT NULL,
  IMPORTE NUMBER(12,2) NOT NULL,
  FECHA_CALCULO DATE NOT NULL,
  AGENTE_DNI VARCHAR2(9) NOT NULL,
  CONSTRAINT PK_COMISION PRIMARY KEY (ID_COMISION),
  CONSTRAINT FK_COMISION_AGENTE FOREIGN KEY (AGENTE_DNI) REFERENCES AGENTE (DNI)
);

COMMENT ON TABLE COMISION IS 'Tabla comision';
COMMENT ON COLUMN COMISION.ID_COMISION IS 'Identificador de la comisicÃ³n';
COMMENT ON COLUMN COMISION.IMPORTE IS 'Importe de la comisiÃ³n';
COMMENT ON COLUMN COMISION.FECHA_CALCULO IS 'Fecha de la comisiÃ³n';
COMMENT ON COLUMN COMISION.AGENTE_DNI IS 'Agente al que le pertenece la comisiÃ³n';


DROP TABLE MOVIMIENTO;
DROP TABLE INMUEBLE_ESTADO;
DROP TABLE INMUEBLE;
DROP TABLE ESTADO;
DROP TABLE COMISION;
DROP TABLE CLIENTE;
DROP TABLE AGENTE;
DROP TABLE HORARIO;
DROP TABLE TIPO_MOVIMIENTO;
DROP TABLE TIPO_INMUEBLE;






