CREATE DATABASE BANCO;
USE BANCO;

CREATE TABLE CLIENTE (
	DNI VARCHAR(9) NOT NULL COMMENT 'DNI del cliente',
    NOMBRE VARCHAR(15) NOT NULL COMMENT 'Nombre del cliente',
    APELLIDOS VARCHAR(30) NOT NULL COMMENT 'Apellidos del cliente',
    DIRECCION VARCHAR (40) NULL COMMENT 'Direccion del cliente',
    TELEFONO VARCHAR(13) NOT NULL COMMENT 'Telefono del cliente',
    CONSTRAINT PK_CLIENTE PRIMARY KEY  (DNI) 
);

CREATE TABLE SUCURSAL (
	ID_SUCURSAL INT NOT NULL AUTO_INCREMENT COMMENT 'ID de la sucursal',
    DIRECCION VARCHAR(30) NOT NULL COMMENT 'Direccion de la sucursal',
    DIRECTOR VARCHAR(30) NOT NULL COMMENT 'Director de la sucursal',
    CONSTRAINT PK_ID_SUCURSAL PRIMARY KEY (ID_SUCURSAL)
);

CREATE TABLE CUENTA (
	NUMERO_CUENTA VARCHAR(35) NOT NULL COMMENT 'Numero de la cuenta',
    FECHA_APERTURA DATE NOT NULL COMMENT 'Fecha de la apertura',
    SALDO DECIMAL(10,2) NOT NULL COMMENT 'Saldo de la cuenta',
	SUCURSAL_ID_SUCURSAL INT NOT NULL COMMENT 'Foreign key de la tabla sucursal',
    CONSTRAINT PK_NUMERO_CUENTA PRIMARY KEY (NUMERO_CUENTA),
    CONSTRAINT FK_CUENTA_SUCURSAL FOREIGN KEY (SUCURSAL_ID_SUCURSAL) REFERENCEs SUCURSAL (ID_SUCURSAL)
);

CREATE TABLE CLIENTE_HAS_CUENTA (
	CLIENTE_DNI VARCHAR(9) NOT NULL COMMENT 'DNI del cliente',
    CUENTA_NUMERO_CUENTA VARCHAR(35) NOT NULL COMMENT 'Numero de la cuenta',
    CONSTRAINT PK_CLIENTE_CUENTA PRIMARY KEY (CLIENTE_DNI, CUENTA_NUMERO_CUENTA),
    CONSTRAINT FK_CLIENTE_CUENTA_CLIENTE FOREIGN KEY (CLIENTE_DNI) REFERENCES CLIENTE (DNI),
    CONSTRAINT FK_CLIENTE_CUENTA_CUENTA FOREIGN KEY (CUENTA_NUMERO_CUENTA) REFERENCES CUENTA (NUMERO_CUENTA)
);

CREATE TABLE TRANSACCION (
	NUMERO_TRANSACCION INT NOT NULL AUTO_INCREMENT COMMENT 'Numero de la transaccion',
    FECHA DATE NULL COMMENT 'Fecha de la transaccion',
    CANTIDAD DECIMAL(10,2) NOT NULL COMMENT 'Cantidad de la transaccion',
    CONSTRAINT PK_TRANSACCION PRIMARY KEY (NUMERO_TRANSACCION)
);

CREATE TABLE CUENTA_HAS_TRANSACCION (
	CUENTA_NUMERO_CUENTA VARCHAR(35) NOT NULL COMMENT 'Numero Cuenta',
    TRANSACCION_NUMERO_TRANSACCION INT NOT NULL COMMENT 'Numero de transaccion',
    CONSTRAINT PK_CUENTA_TRANSACCION PRIMARY KEY (CUENTA_NUMERO_CUENTA, TRANSACCION_NUMERO_TRANSACCION),
    CONSTRAINT FK_CUENTA_NUMERO_CUENTA FOREIGN KEY (CUENTA_NUMERO_CUENTA) REFERENCES CUENTA (NUMERO_CUENTA),
    CONSTRAINT KF_TRANSACCION_NUMERO_TRANSACCION FOREIGN KEY (TRANSACCION_NUMERO_TRANSACCION) REFERENCES TRANSACCION (NUMERO_TRANSACCION)
);







