DROP DATABASE IF EXISTS PRUEBA_TRANSVERSAL;
CREATE DATABASE PRUEBA_TRANSVERSAL;
USE PRUEBA_TRANSVERSAL;

-- Tabla de usuario
CREATE TABLE USUARIO (
	USER_NAME VARCHAR(25) NOT NULL COMMENT 'Nombre del usuario del casino',
    USER_PASSWORD VARCHAR(10) NOT NULL COMMENT 'Contraseña del usuario',
    CONSTRAINT PK_USUARIO PRIMARY KEY (USER_NAME)
);
