DROP TABLE USUARIOS;
DROP TABLE ROLES;

DROP TABLE ALMACEN;
DROP TABLE VENTAS;
DROP TABLE PRODUCTOS;
DROP TABLE TIPO;
DROP TABLE COMERCIALES;
DROP TABLE FAMILIA;

DROP TABLE CLIENTES;
DROP TABLE DIRECCION_POSTAL;
DROP TABLE LOCALIDAD;
DROP TABLE PROVINCIA;