DELETE FROM USUARIOS;
DELETE FROM ROLES;

DELETE FROM ALMACEN;
DELETE FROM VENTAS;
DELETE FROM PRODUCTOS;
DELETE FROM TIPO;
DELETE FROM COMERCIALES;
DELETE FROM FAMILIA;

DELETE FROM CLIENTES;
DELETE FROM DIRECCION_POSTAL;
DELETE FROM LOCALIDAD;
DELETE FROM PROVINCIA;