CREATE TABLE ROLES (
    ID_ROL VARCHAR2(20),
    DESCRIPCION_ROL VARCHAR2(30) NOT NULL,
    CONSTRAINT PK_ROLES PRIMARY KEY (ID_ROL)
);

COMMENT ON TABLE ROLES IS 'Tabla Roles';
COMMENT ON COLUMN ROLES.ID_ROL IS 'Identificador de la tabla ROLES';

CREATE TABLE USUARIOS (
    ID_USUARIOS VARCHAR2(50),
    DESCRIPCION_USUARIO VARCHAR2(70) NOT NULL,
    EMAIL VARCHAR2(100)NOT NULL,
    PASSWD VARCHAR2(250) NOT NULL,
    ID_ROL VARCHAR2(30)NOT NULL,
    CONSTRAINT PK_USUARIOS PRIMARY KEY (ID_USUARIOS),
    CONSTRAINT FK_ROLES FOREIGN KEY (ID_ROL) REFERENCES ROLES (ID_ROL)
);

COMMENT ON TABLE USUARIOS IS 'Tabla USUARIOS';
COMMENT ON COLUMN USUARIOS.ID_USUARIOS IS 'Identificador de la tabla USUARIOS';
COMMENT ON COLUMN USUARIOS.DESCRIPCION_USUARIO IS 'Campo de la tabla USUARIOS';
COMMENT ON COLUMN USUARIOS.EMAIL IS 'Campo de la tabla USUARIOS';
COMMENT ON COLUMN USUARIOS.PASSWD IS 'Campo de la tabla USUARIOS';
COMMENT ON COLUMN USUARIOS.ID_ROL IS 'Foreign Key de la tabla USUARIOS';


CREATE TABLE PROVINCIA (
    ID_PROVINCIA NUMBER,
    DESCRIPCION_PROVINCIA VARCHAR2(70) NOT NULL,
    CONSTRAINT PK_PROVINCIA PRIMARY KEY  (ID_PROVINCIA)
);

COMMENT ON TABLE PROVINCIA IS 'Tabla PROVINCIA';
COMMENT ON COLUMN PROVINCIA.ID_PROVINCIA IS 'Identificador de la tabla PROVINCIA';
COMMENT ON COLUMN PROVINCIA.DESCRIPCION_PROVINCIA IS 'Campo de la tabla PROVINCIA';

CREATE TABLE FAMILIA (
    ID_FAMILIA NUMBER,
    DESCRIPCION VARCHAR2(60),
    CONSTRAINT PK_FAMILIA PRIMARY KEY (ID_FAMILIA)
);

COMMENT ON TABLE FAMILIA IS 'Tabla FAMILIA';
COMMENT ON COLUMN FAMILIA.ID_FAMILIA IS 'Identificador de la tabla FAMILIA';
COMMENT ON COLUMN FAMILIA.DESCRIPCION IS 'Campo de la tabla FAMILIA';

CREATE TABLE COMERCIALES (
    ID_COMERCIAL VARCHAR2(20),
    DESCRIPCION_COMERCIAL VARCHAR2(30),
    SUELDO_BASE NUMBER,
    COMISION NUMBER,
    CONSTRAINT PK_COMERCIALES PRIMARY KEY (ID_COMERCIAL)
);

COMMENT ON TABLE COMERCIALES IS 'Tabla COMERCIALES';
COMMENT ON COLUMN COMERCIALES.ID_COMERCIAL IS 'Identificador de la tabla COMERCIALES';
COMMENT ON COLUMN COMERCIALES.DESCRIPCION_COMERCIAL IS 'Campo de la tabla COMERCIALES';
COMMENT ON COLUMN COMERCIALES.SUELDO_BASE IS 'Campo de la tabla COMERCIALES';
COMMENT ON COLUMN COMERCIALES.COMISION IS 'Campo de la tabla COMERCIALES';

CREATE TABLE LOCALIDAD (
    ID_LOCALIDAD NUMBER,
    DESCRIPCION_LOCALIDAD VARCHAR2(70),
    ID_PROVINCIA NUMBER,
    CONSTRAINT PK_LOCALIDAD PRIMARY KEY (ID_LOCALIDAD),
    CONSTRAINT FK_PROVINCIA FOREIGN KEY (ID_PROVINCIA) REFERENCES PROVINCIA (ID_PROVINCIA)
);

COMMENT ON TABLE LOCALIDAD IS 'Tabla LOCALIDAD';
COMMENT ON COLUMN LOCALIDAD.ID_LOCALIDAD IS 'Identificador de la tabla LOCALIDAD';
COMMENT ON COLUMN LOCALIDAD.DESCRIPCION_LOCALIDAD IS 'Campo de la tabla LOCALIDAD';
COMMENT ON COLUMN LOCALIDAD.ID_PROVINCIA IS 'Foreign Key de la tabla LOCALIDAD';


CREATE TABLE DIRECCION_POSTAL (
    ID_DIRECCION NUMBER,
    CALLE VARCHAR2(350)NOT NULL,
    NUMERO NUMBER NOT NULL,
    PISO NUMBER NOT NULL,
    LETRA VARCHAR2(1) NOT NULL,
    CP NUMBER NOT NULL,
    ID_LOCALIDAD NUMBER,
    ID_PROVINCIA NUMBER,
    CONSTRAINT PK_DIRECCION_POSTAL PRIMARY KEY (ID_DIRECCION),
    CONSTRAINT FK_ID_LOCALIDAD FOREIGN KEY (ID_LOCALIDAD) REFERENCES LOCALIDAD (ID_LOCALIDAD),
    CONSTRAINT FK_ID_PROVINCIA  FOREIGN KEY (ID_PROVINCIA) REFERENCES PROVINCIA  (ID_PROVINCIA)
);

COMMENT ON TABLE DIRECCION_POSTAL IS 'Tabla DIRECCION_POSTAL';
COMMENT ON COLUMN DIRECCION_POSTAL.ID_DIRECCION IS 'Identificador de la tabla DIRECCION_POSTAL';
COMMENT ON COLUMN DIRECCION_POSTAL.CALLE IS 'Campo de la tabla DIRECCION_POSTAL';
COMMENT ON COLUMN DIRECCION_POSTAL.NUMERO IS 'Campo de la tabla DIRECCION_POSTAL';
COMMENT ON COLUMN DIRECCION_POSTAL.PISO IS 'Campo de la tabla DIRECCION_POSTAL';
COMMENT ON COLUMN DIRECCION_POSTAL.LETRA IS 'Campo de la tabla DIRECCION_POSTAL';
COMMENT ON COLUMN DIRECCION_POSTAL.CP IS 'Campo de la tabla DIRECCION_POSTAL';
COMMENT ON COLUMN DIRECCION_POSTAL.ID_LOCALIDAD IS 'Foreign Key de la tabla DIRECCION_POSTAL';
COMMENT ON COLUMN DIRECCION_POSTAL.ID_PROVINCIA IS 'Foreign Key de la tabla DIRECCION_POSTAL';


CREATE TABLE TIPO (
    ID_TIPO NUMBER,
    DESCRIPCION_TIPO VARCHAR2(100) NOT NULL,
    ID_FAMILIA NUMBER,
    CONSTRAINT PK_TIPO PRIMARY KEY (ID_TIPO),
    CONSTRAINT FK_ID_FAMILIA FOREIGN KEY (ID_TIPO) REFERENCES FAMILIA (ID_FAMILIA)
);

COMMENT ON TABLE TIPO IS 'Tabla TIPO';
COMMENT ON COLUMN TIPO.ID_TIPO IS 'Identificador de la tabla TIPO';
COMMENT ON COLUMN TIPO.DESCRIPCION_TIPO IS 'Campo de la tabla TIPO';
COMMENT ON COLUMN TIPO.ID_FAMILIA IS 'Foreign Key de la tabla TIPO';


CREATE TABLE CLIENTES (
    ID_DNI VARCHAR2(15),
    NOMBRE VARCHAR2(50) NOT NULL,
    APELLIDO1 VARCHAR2(70) NOT NULL,
    APELLIDO2 VARCHAR2(70) NOT NULL,
    FECHA_NACIMIENTO DATE NOT NULL,
    ESTADO_CIVIL VARCHAR2(2),
    EDAD NUMBER,
    ID_DIRECCION NUMBER,
    CONSTRAINT PK_CLIENTES PRIMARY KEY (ID_DNI),
    CONSTRAINT FK_ID_DIRECCION FOREIGN KEY (ID_DIRECCION) REFERENCES DIRECCION_POSTAL (ID_DIRECCION)
);

COMMENT ON TABLE CLIENTES IS 'Tabla CLIENTES';
COMMENT ON COLUMN CLIENTES.ID_DNI IS 'Identificador de la tabla CLIENTES';
COMMENT ON COLUMN CLIENTES.NOMBRE IS 'Campo de la tabla CLIENTES';
COMMENT ON COLUMN CLIENTES.APELLIDO1 IS 'Campo de la tabla CLIENTES';
COMMENT ON COLUMN CLIENTES.APELLIDO2 IS 'Campo de la tabla CLIENTES';
COMMENT ON COLUMN CLIENTES.FECHA_NACIMIENTO IS 'Campo de la tabla CLIENTES';
COMMENT ON COLUMN CLIENTES.ESTADO_CIVIL IS 'Campo de la tabla CLIENTES';
COMMENT ON COLUMN CLIENTES.EDAD IS 'Campo de la tabla CLIENTES';
COMMENT ON COLUMN CLIENTES.ID_DIRECCION IS 'Foreign Key de la tabla CLIENTES';

CREATE TABLE PRODUCTOS (
    ID_PRODUCTO NUMBER,
    DESCRIPCION_PRODUCTO VARCHAR2(70) NOT NULL,
    ID_TIPO NUMBER,
    PRECIO NUMBER NOT NULL,
    CONSTRAINT PK_PRODUCTOS PRIMARY KEY (ID_PRODUCTO),
    CONSTRAINT FK_ID_TIPO FOREIGN KEY (ID_TIPO) REFERENCES TIPO (ID_TIPO)
);

COMMENT ON TABLE PRODUCTOS IS 'Tabla PRODUCTOS';
COMMENT ON COLUMN PRODUCTOS.ID_PRODUCTO IS 'Identificador de la tabla PRODUCTOS';
COMMENT ON COLUMN PRODUCTOS.DESCRIPCION_PRODUCTO IS 'Campo de la tabla PRODUCTOS';
COMMENT ON COLUMN PRODUCTOS.PRECIO IS 'Campo de la tabla PRODUCTOS';
COMMENT ON COLUMN PRODUCTOS.ID_TIPO IS 'Foreign Key de la tabla CLIENTES';

CREATE TABLE ALMACEN (
    ID_ALMACEN NUMBER,
    ID_PRODUCTO NUMBER,
    CANTIDAD NUMBER,
    CONSTRAINT PK_ALMACEN PRIMARY KEY (ID_ALMACEN),
    CONSTRAINT FK_ID_PRODUCTOS FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS (ID_PRODUCTO)
);

COMMENT ON TABLE ALMACEN IS 'Tabla ALMACEN';
COMMENT ON COLUMN ALMACEN.ID_ALMACEN IS 'Identificador de la tabla ALMACEN';
COMMENT ON COLUMN ALMACEN.CANTIDAD IS 'Campo de la tabla ALMACEN';
COMMENT ON COLUMN ALMACEN.ID_PRODUCTO IS 'Foreign Key de la tabla ALMACEN';

CREATE TABLE VENTAS (
    ID_VENTAS NUMBER,
    ID_PRODUCTO NUMBER,
    ID_DNI VARCHAR2(15),
    FEC_VENTA DATE NOT NULL,
    CANTIDAD NUMBER NOT NULL,
    CONSTRAINT PK_VENTAS PRIMARY KEY (ID_VENTAS),
    CONSTRAINT FK_ID_CLIENTES FOREIGN KEY (ID_DNI) REFERENCES CLIENTES (ID_DNI),
    CONSTRAINT FK_ID_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS (ID_PRODUCTO)
);

COMMENT ON TABLE VENTAS IS 'Tabla VENTAS';
COMMENT ON COLUMN VENTAS.ID_VENTAS IS 'Identificador de la tabla VENTAS';
COMMENT ON COLUMN VENTAS.CANTIDAD IS 'Campo de la tabla VENTAS';
COMMENT ON COLUMN VENTAS.FEC_VENTA IS 'Campo de la tabla VENTAS';
COMMENT ON COLUMN VENTAS.ID_PRODUCTO IS 'Foreign Key de la tabla VENTAS';
COMMENT ON COLUMN VENTAS.ID_DNI IS 'Foreign Key de la tabla VENTAS';