ALTER TABLE ALMACEN
MODIFY ID_PRODUCTO NOT NULL;

ALTER TABLE ALMACEN
MODIFY CANTIDAD NOT NULL;

ALTER TABLE CLIENTES
MODIFY NOMBRE VARCHAR2(100);

ALTER TABLE CLIENTES
MODIFY APELLIDO1 VARCHAR2(150);

ALTER TABLE CLIENTES
MODIFY APELLIDO2 VARCHAR2(150);

ALTER TABLE CLIENTES
MODIFY FECHA_NACIMIENTO NULL;

ALTER TABLE DIRECCION_POSTAL
ADD ESCALERA VARCHAR2(20);

COMMENT ON TABLE DIRECCION_POSTAL IS 'Se anadio una columna nueva';
COMMENT ON COLUMN DIRECCION_POSTAL.ESCALERA IS 'Nueva columna';

ALTER TABLE PRODUCTOS
ADD PAGO_PLAZOS VARCHAR2(1);

COMMENT ON TABLE PRODUCTOS IS 'Se anadio una nueva columna';
COMMENT ON COLUMN PRODUCTOS.PAGO_PLAZOS IS 'Nueva columna';