DROP DATABASE IF EXISTS MAYORISTAS;
CREATE DATABASE MAYORISTAS;
USE MAYORISTAS;

-- Ejercicio 1

CREATE TABLE CLIENTE (
  ID_CLIENTE INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador del cliente',
  NOMBRE VARCHAR(50) NOT NULL COMMENT 'Nombre del cliente',
  CIUDAD VARCHAR(100) NOT NULL COMMENT 'Ciudad del cliente',
  CONSTRAINT PK_CLIENTE PRIMARY KEY (ID_CLIENTE)
) COMMENT 'Datos de los clientes';

CREATE TABLE HOTEL (
  ID_HOTEL INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador del hotel',
  NOMBRE VARCHAR(50) NOT NULL COMMENT 'Nombre del hotel',
  CATEGORIA INT NOT NULL COMMENT 'Categoria del hotel',
  CIUDAD VARCHAR(100) NOT NULL COMMENT 'Ciudad del hotel',
  CONSTRAINT PK_HOTEL PRIMARY KEY (ID_HOTEL)
) COMMENT 'Datos de los hoteles';

CREATE TABLE AGENCIA (
  ID_AGENCIA INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador de la agencia',
  NOMBRE VARCHAR(50) NOT NULL COMMENT 'Nombre de la agencia',
  CIUDAD VARCHAR(100) NOT NULL COMMENT 'Ciudad donde se encuentra la agencia',
  IS_ONLINE INT(1) NOT NULL COMMENT '0: La Agencia es física / 1: La Agencia es online',
  CONSTRAINT PK_AGENCIA PRIMARY KEY (ID_AGENCIA)
) COMMENT 'Datos de las agencias de viajes';

CREATE TABLE PRODUCTO (
  ID_PRODUCTO INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador del producto que vende la agencia',
  ID_HOTEL INT NULL COMMENT 'En el caso que el producto sea un hotel, este será el identificador',
  ID_AGENCIA INT NOT NULL COMMENT 'Identificador de la agencia que se encargar de vender el producto',
  CONSTRAINT PK_PRODUCTO PRIMARY KEY (ID_PRODUCTO),
  CONSTRAINT FK_PRODUCTO_ID_HOTEL FOREIGN KEY(ID_HOTEL) REFERENCES HOTEL(ID_HOTEL),
  CONSTRAINT FK_PRODUCTO_ID_AGENCIA FOREIGN KEY(ID_AGENCIA) REFERENCES AGENCIA(ID_AGENCIA)
) COMMENT 'Datos de los productos de las agencias de viajes';

CREATE TABLE AGENTE (
  DNI VARCHAR(9) NOT NULL COMMENT 'DNI del Agente',
  EMAIL VARCHAR(100) NULL COMMENT 'Dirección de correo electrónico del Agente',
  TELEFONO VARCHAR(15) NOT NULL COMMENT 'Telefono del Agente',
  NOMBRE VARCHAR(50) NOT NULL COMMENT 'Nombre del Agente',
  APELLIDOS VARCHAR(150) NOT NULL COMMENT 'Apellidos del Agente',
  SALARIO_BASE DECIMAL(12) NOT NULL COMMENT 'Salario base del Agente',
  OBSERVACIONES VARCHAR(300) NULL COMMENT 'Observaciones del Agente',
  CONSTRAINT PK_AGENTE PRIMARY KEY (DNI)
) COMMENT 'Datos de los trabajadores de las agencias de viajes';

CREATE TABLE RESERVA (
  ID_RESERVA INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador de la reserva',
  FECHA_RESERVA DATETIME NOT NULL COMMENT 'Fecha comienzo de la reserva',
  NUM_DIAS INT NOT NULL COMMENT 'Numero de dias de la reserva',
  IMPORTE_RESERVA DECIMAL(8,2) NOT NULL COMMENT 'Importe de la reserva',
  ID_CLIENTE INT NOT NULL COMMENT 'Identificador del cliente que realiza la reserva',
  ID_PRODUCTO INT NOT NULL COMMENT 'Identificador del producto que se reserva',
  DNI_AGENTE VARCHAR(9) NULL COMMENT 'Agente a traves del cual se realiza la reserva (solo si no es online)',
  CONSTRAINT PK_RESERVA PRIMARY KEY (ID_RESERVA),
  CONSTRAINT FK_RESERVA_ID_CLIENTE FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
  CONSTRAINT FK_RESERVA_ID_PRODUCTO FOREIGN KEY(ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO),
  CONSTRAINT FK_RESERVA_AGENTE FOREIGN KEY(DNI_AGENTE) REFERENCES AGENTE(DNI)
) COMMENT 'Datos de las reservas realizadas por un cliente, de un producto, por cada agente';


-- Ejercicio 2

INSERT INTO CLIENTE (NOMBRE, CIUDAD) VALUES ('Juan Murray','Madrid');
INSERT INTO CLIENTE (NOMBRE, CIUDAD) VALUES ('Rosario Lopez','Madrid');
INSERT INTO CLIENTE (NOMBRE, CIUDAD) VALUES ('Pedro Lopez','Toledo');
INSERT INTO CLIENTE (NOMBRE, CIUDAD) VALUES ('Amelia Sanchez','Cuenca');

INSERT INTO HOTEL (NOMBRE, CATEGORIA, CIUDAD) VALUES ('Fiesta INN',4, 'Madrid');
INSERT INTO HOTEL (NOMBRE, CATEGORIA, CIUDAD) VALUES ('Camino Real',5, 'Toledo');
INSERT INTO HOTEL (NOMBRE, CATEGORIA, CIUDAD) VALUES ('Mirador', 3, 'Alicante');
    
INSERT INTO AGENCIA (NOMBRE, CIUDAD, IS_ONLINE) VALUES ('Atrapalo','Madrid', 1);
INSERT INTO AGENCIA (NOMBRE, CIUDAD, IS_ONLINE) VALUES ('Destinia','Madrid', 1);
INSERT INTO AGENCIA (NOMBRE, CIUDAD, IS_ONLINE) VALUES ('Rumbo','Barcelona', 1);
INSERT INTO AGENCIA (NOMBRE, CIUDAD, IS_ONLINE) VALUES ('Catai','Madrid', 0);
INSERT INTO AGENCIA (NOMBRE, CIUDAD, IS_ONLINE) VALUES ('Horizonte Paralelo','Toledo', 0);
    
INSERT INTO PRODUCTO (ID_HOTEL, ID_AGENCIA) VALUES (1, 1);
INSERT INTO PRODUCTO (ID_HOTEL, ID_AGENCIA) VALUES (1, 2);
INSERT INTO PRODUCTO (ID_HOTEL, ID_AGENCIA) VALUES (1, 3);
INSERT INTO PRODUCTO (ID_HOTEL, ID_AGENCIA) VALUES (1, 4);
INSERT INTO PRODUCTO (ID_HOTEL, ID_AGENCIA) VALUES (1, 5);
INSERT INTO PRODUCTO (ID_HOTEL, ID_AGENCIA) VALUES (2, 1);
INSERT INTO PRODUCTO (ID_HOTEL, ID_AGENCIA) VALUES (2, 2);
INSERT INTO PRODUCTO (ID_HOTEL, ID_AGENCIA) VALUES (2, 3);
INSERT INTO PRODUCTO (ID_HOTEL, ID_AGENCIA) VALUES (2, 4);
INSERT INTO PRODUCTO (ID_HOTEL, ID_AGENCIA) VALUES (2, 5);
INSERT INTO PRODUCTO (ID_HOTEL, ID_AGENCIA) VALUES (3, 1);
INSERT INTO PRODUCTO (ID_HOTEL, ID_AGENCIA) VALUES (3, 2);
INSERT INTO PRODUCTO (ID_HOTEL, ID_AGENCIA) VALUES (3, 3);
INSERT INTO PRODUCTO (ID_HOTEL, ID_AGENCIA) VALUES (3, 4);
INSERT INTO PRODUCTO (ID_HOTEL, ID_AGENCIA) VALUES (3, 5);
    
INSERT INTO AGENTE(DNI, EMAIL, TELEFONO, NOMBRE, APELLIDOS, SALARIO_BASE, OBSERVACIONES) VALUES ('41275026C', 'agente@catai.es','901789521','Leonor','Aranguez',2100,'Agente de ventas');
INSERT INTO AGENTE(DNI, EMAIL, TELEFONO, NOMBRE, APELLIDOS, SALARIO_BASE, OBSERVACIONES) VALUES ('06847101D', 'agente@horizonte.es','900112233','Laura','Cruz',1400,'Agente de ventas');
    
INSERT INTO RESERVA (FECHA_RESERVA, NUM_DIAS, IMPORTE_RESERVA, ID_CLIENTE, ID_PRODUCTO, DNI_AGENTE) VALUES ('2020/05/01', 2, 150, 1, 1, NULL);
INSERT INTO RESERVA (FECHA_RESERVA, NUM_DIAS, IMPORTE_RESERVA, ID_CLIENTE, ID_PRODUCTO, DNI_AGENTE) VALUES ('2020/05/01', 2, 210, 2, 2, NULL);
INSERT INTO RESERVA (FECHA_RESERVA, NUM_DIAS, IMPORTE_RESERVA, ID_CLIENTE, ID_PRODUCTO, DNI_AGENTE) VALUES ('2020/06/10', 7, 600, 3, 6, NULL);
INSERT INTO RESERVA (FECHA_RESERVA, NUM_DIAS, IMPORTE_RESERVA, ID_CLIENTE, ID_PRODUCTO, DNI_AGENTE) VALUES ('2020/07/15', 7, 1200, 3, 4, '41275026C');

-- Ejercicio 3

CREATE TABLE TIPO_TRANSPORTE (
 TIPO_TRANSPORTE VARCHAR(10) NOT NULL COMMENT 'Identificador del tipo de transporte',
 NOMBRE VARCHAR(50) NOT NULL COMMENT 'Nombre del tipo de transporte',
 DESCRIPCION VARCHAR(100) NULL COMMENT 'Descripcion del tipo de transporte',
 CONSTRAINT PK_TIPO_TRANSPORTE PRIMARY KEY (TIPO_TRANSPORTE)
) COMMENT 'Datos de tipos de transporte';

CREATE TABLE TRANSPORTE (
 ID_TRANSPORTE INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador del transporte',
 ORIGEN VARCHAR(50) NOT NULL COMMENT 'Origen del transporte',
 DESTINO VARCHAR(100) NULL COMMENT 'Destino del transporte',
 TIPO_TRANSPORTE VARCHAR(10) NOT NULL COMMENT 'Tipo del transporte', 
 CONSTRAINT PK_TRANSPORTE PRIMARY KEY (ID_TRANSPORTE),
 CONSTRAINT FK_TRANSPORTE_TIPO_TRANSPORTE FOREIGN KEY (TIPO_TRANSPORTE) REFERENCES TIPO_TRANSPORTE(TIPO_TRANSPORTE)
) COMMENT 'Datos de los transportes';


-- Ejercicio 4

ALTER TABLE PRODUCTO 
ADD COLUMN ID_TRANSPORTE INT NULL COMMENT 'Producto de tipo Transporte',
ADD CONSTRAINT FK_PRODUCTO_ID_TRANSPORTE FOREIGN KEY(ID_TRANSPORTE) REFERENCES TRANSPORTE(ID_TRANSPORTE);

ALTER TABLE CLIENTE 
MODIFY COLUMN NOMBRE VARCHAR(100) NOT NULL;


-- Ejercicio 5

INSERT INTO TIPO_TRANSPORTE (TIPO_TRANSPORTE, NOMBRE, DESCRIPCION) 
VALUES ('TR00000001','Autobus','Transporte en autobus');
INSERT INTO TIPO_TRANSPORTE (TIPO_TRANSPORTE, NOMBRE, DESCRIPCION) 
VALUES ('TR00000002','Tren','Transporte en tren');
INSERT INTO TIPO_TRANSPORTE (TIPO_TRANSPORTE, NOMBRE, DESCRIPCION) 
VALUES ('TR00000003','Avion',null);
INSERT INTO TRANSPORTE (ORIGEN, DESTINO, TIPO_TRANSPORTE) 
VALUES ('Valladolid','Madrid','TR00000002');
INSERT INTO TRANSPORTE (ORIGEN, DESTINO, TIPO_TRANSPORTE) 
VALUES ('Ciudad Real','Toledo','TR00000001');
INSERT INTO TRANSPORTE (ORIGEN, DESTINO, TIPO_TRANSPORTE) 
VALUES ('Ciudad Real','Alicante','TR00000002');