
CREATE TABLE CLIENTE (
	ID_CLIENTE NUMBER NOT NULL,
  NOMBRE VARCHAR2(50),
  CIUDAD VARCHAR2(100) NOT NULL,
  CONSTRAINT PK_CLIENTE PRIMARY KEY (ID_CLIENTE)
);

COMMENT ON TABLE CLIENTE IS 'Datos de los clientes';
COMMENT ON COLUMN CLIENTE.ID_CLIENTE IS 'Identificador del cliente';
COMMENT ON COLUMN CLIENTE.NOMBRE IS 'Nombre del cliente';
COMMENT ON COLUMN CLIENTE.CIUDAD IS 'Ciudad del cliente';

CREATE SEQUENCE SEC_CLIENTE
INCREMENT BY 1
START WITH 1
MAXVALUE 999999999
NOCACHE
ORDER;

INSERT INTO CLIENTE (ID_CLIENTE, NOMBRE, CIUDAD) VALUES (SEC_CLIENTE.NEXTVAL, 'Juan Murray','Madrid');
INSERT INTO CLIENTE (ID_CLIENTE, NOMBRE, CIUDAD) VALUES (SEC_CLIENTE.NEXTVAL, 'Rosario Lopez','Madrid');
INSERT INTO CLIENTE (ID_CLIENTE, NOMBRE, CIUDAD) VALUES (SEC_CLIENTE.NEXTVAL, 'Pedro Lopez','Toledo');
INSERT INTO CLIENTE (ID_CLIENTE, NOMBRE, CIUDAD) VALUES (SEC_CLIENTE.NEXTVAL, 'Amelia Sanchez','Cuenca');

COMMIT;
   
CREATE TABLE HOTEL (
  ID_HOTEL NUMBER NOT NULL,
  NOMBRE VARCHAR2(50) NOT NULL,
  CATEGORIA NUMBER NOT NULL,
  CIUDAD VARCHAR2(100) NOT NULL,
  CONSTRAINT PK_HOTEL PRIMARY KEY (ID_HOTEL)
);

COMMENT ON TABLE HOTEL IS 'Datos de los hoteles';
COMMENT ON COLUMN HOTEL.ID_HOTEL IS 'Identificador del hotel';
COMMENT ON COLUMN HOTEL.NOMBRE IS 'Nombre del hotel';
COMMENT ON COLUMN HOTEL.CATEGORIA IS 'Categoria del hotel';
COMMENT ON COLUMN HOTEL.CIUDAD IS 'Ciudad del hotel';

CREATE SEQUENCE SEC_HOTEL
INCREMENT BY 1
START WITH 1
MAXVALUE 999999999
NOCACHE
ORDER;

INSERT INTO HOTEL (ID_HOTEL, NOMBRE, CATEGORIA, CIUDAD) VALUES (SEC_HOTEL.NEXTVAL, 'Fiesta INN',4, 'Madrid');
INSERT INTO HOTEL (ID_HOTEL, NOMBRE, CATEGORIA, CIUDAD) VALUES (SEC_HOTEL.NEXTVAL, 'Camino Real',5, 'Toledo');
INSERT INTO HOTEL (ID_HOTEL, NOMBRE, CATEGORIA, CIUDAD) VALUES (SEC_HOTEL.NEXTVAL, 'Mirador', 3, 'Alicante');

COMMIT;

CREATE TABLE AGENCIA (
	ID_AGENCIA NUMBER NOT NULL,
  NOMBRE VARCHAR2(50) NOT NULL,
  CIUDAD VARCHAR2(100) NOT NULL,
  IS_ONLINE NUMBER(1) NOT NULL,
  CONSTRAINT PK_AGENCIA PRIMARY KEY (ID_AGENCIA)
);

COMMENT ON TABLE AGENCIA IS 'Datos de las agencias de viajes';
COMMENT ON COLUMN AGENCIA.ID_AGENCIA IS 'Identificador de la agencia';
COMMENT ON COLUMN AGENCIA.NOMBRE IS 'Nombre de la agencia';
COMMENT ON COLUMN AGENCIA.CIUDAD IS 'Ciudad donde se encuentra la agencia';
COMMENT ON COLUMN AGENCIA.IS_ONLINE IS '0: La Agencia es física / 1: La Agencia es online';

CREATE SEQUENCE SEC_AGENCIA
INCREMENT BY 1
START WITH 1
MAXVALUE 999999999
NOCACHE
ORDER;

INSERT INTO AGENCIA (ID_AGENCIA, NOMBRE, CIUDAD, IS_ONLINE) VALUES (SEC_AGENCIA.NEXTVAL, 'Atrapalo','Madrid', 1);
INSERT INTO AGENCIA (ID_AGENCIA, NOMBRE, CIUDAD, IS_ONLINE) VALUES (SEC_AGENCIA.NEXTVAL, 'Destinia','Madrid', 1);
INSERT INTO AGENCIA (ID_AGENCIA, NOMBRE, CIUDAD, IS_ONLINE) VALUES (SEC_AGENCIA.NEXTVAL, 'Rumbo','Barcelona', 1);
INSERT INTO AGENCIA (ID_AGENCIA, NOMBRE, CIUDAD, IS_ONLINE) VALUES (SEC_AGENCIA.NEXTVAL, 'Catai','Madrid', 0);
INSERT INTO AGENCIA (ID_AGENCIA, NOMBRE, CIUDAD, IS_ONLINE) VALUES (SEC_AGENCIA.NEXTVAL, 'Horizonte Paralelo','Toledo', 0);

COMMIT;

CREATE TABLE PRODUCTO (
	ID_PRODUCTO NUMBER NOT NULL,
  ID_HOTEL NUMBER,
  ID_AGENCIA NUMBER NOT NULL,
  CONSTRAINT PK_PRODUCTO PRIMARY KEY (ID_PRODUCTO),
  CONSTRAINT FK_PRODUCTO_ID_HOTEL FOREIGN KEY(ID_HOTEL) REFERENCES HOTEL(ID_HOTEL),
  CONSTRAINT FK_PRODUCTO_ID_AGENCIA FOREIGN KEY(ID_AGENCIA) REFERENCES AGENCIA(ID_AGENCIA)
);

COMMENT ON TABLE PRODUCTO IS 'Datos de los productos de las agencias de viajes';
COMMENT ON COLUMN PRODUCTO.ID_PRODUCTO IS 'Identificador del producto que vende la agencia';
COMMENT ON COLUMN PRODUCTO.ID_HOTEL IS 'En el caso que el producto sea un hotel, este será el identificador';
COMMENT ON COLUMN PRODUCTO.ID_AGENCIA IS 'Identificador de la agencia que se encargar de vender el producto';

CREATE SEQUENCE SEC_PRODUCTO
INCREMENT BY 1
START WITH 1
MAXVALUE 999999999
NOCACHE
ORDER;

INSERT INTO PRODUCTO (ID_PRODUCTO, ID_HOTEL, ID_AGENCIA) VALUES (SEC_PRODUCTO.NEXTVAL, 1, 1);
INSERT INTO PRODUCTO (ID_PRODUCTO, ID_HOTEL, ID_AGENCIA) VALUES (SEC_PRODUCTO.NEXTVAL, 1, 2);
INSERT INTO PRODUCTO (ID_PRODUCTO, ID_HOTEL, ID_AGENCIA) VALUES (SEC_PRODUCTO.NEXTVAL, 1, 3);
INSERT INTO PRODUCTO (ID_PRODUCTO, ID_HOTEL, ID_AGENCIA) VALUES (SEC_PRODUCTO.NEXTVAL, 1, 4);
INSERT INTO PRODUCTO (ID_PRODUCTO, ID_HOTEL, ID_AGENCIA) VALUES (SEC_PRODUCTO.NEXTVAL, 1, 5);
INSERT INTO PRODUCTO (ID_PRODUCTO, ID_HOTEL, ID_AGENCIA) VALUES (SEC_PRODUCTO.NEXTVAL, 2, 1);
INSERT INTO PRODUCTO (ID_PRODUCTO, ID_HOTEL, ID_AGENCIA) VALUES (SEC_PRODUCTO.NEXTVAL, 2, 2);
INSERT INTO PRODUCTO (ID_PRODUCTO, ID_HOTEL, ID_AGENCIA) VALUES (SEC_PRODUCTO.NEXTVAL, 2, 3);
INSERT INTO PRODUCTO (ID_PRODUCTO, ID_HOTEL, ID_AGENCIA) VALUES (SEC_PRODUCTO.NEXTVAL, 2, 4);
INSERT INTO PRODUCTO (ID_PRODUCTO, ID_HOTEL, ID_AGENCIA) VALUES (SEC_PRODUCTO.NEXTVAL, 2, 5);
INSERT INTO PRODUCTO (ID_PRODUCTO, ID_HOTEL, ID_AGENCIA) VALUES (SEC_PRODUCTO.NEXTVAL, 3, 1);
INSERT INTO PRODUCTO (ID_PRODUCTO, ID_HOTEL, ID_AGENCIA) VALUES (SEC_PRODUCTO.NEXTVAL, 3, 2);
INSERT INTO PRODUCTO (ID_PRODUCTO, ID_HOTEL, ID_AGENCIA) VALUES (SEC_PRODUCTO.NEXTVAL, 3, 3);
INSERT INTO PRODUCTO (ID_PRODUCTO, ID_HOTEL, ID_AGENCIA) VALUES (SEC_PRODUCTO.NEXTVAL, 3, 4);
INSERT INTO PRODUCTO (ID_PRODUCTO, ID_HOTEL, ID_AGENCIA) VALUES (SEC_PRODUCTO.NEXTVAL, 3, 5);

COMMIT;

-- -----------------------------------------------------
-- Table AGENTES de las Agencias que no son online
-- -----------------------------------------------------
CREATE TABLE AGENTE (
  DNI VARCHAR2(9) NOT NULL,
  EMAIL VARCHAR2(100),
  TELEFONO VARCHAR2(15) NOT NULL,
  NOMBRE VARCHAR2(50) NOT NULL,
  APELLIDOS VARCHAR2(150) NOT NULL,
  SALARIO_BASE NUMBER(12) NOT NULL,
  OBSERVACIONES VARCHAR2(300),
  CONSTRAINT PK_AGENTE PRIMARY KEY (DNI)
);

COMMENT ON TABLE AGENTE IS 'Datos de los trabajadores de las agencias de viajes';
COMMENT ON COLUMN AGENTE.DNI IS 'DNI del Agente';
COMMENT ON COLUMN AGENTE.EMAIL IS 'Dirección de correo electrónico del Agente';
COMMENT ON COLUMN AGENTE.TELEFONO IS 'Telefono del Agente';
COMMENT ON COLUMN AGENTE.NOMBRE IS 'Nombre del Agente';
COMMENT ON COLUMN AGENTE.APELLIDOS IS 'Apellidos del Agente';
COMMENT ON COLUMN AGENTE.SALARIO_BASE IS 'Salario base del Agente';
COMMENT ON COLUMN AGENTE.OBSERVACIONES IS 'Observaciones del Agente';

INSERT INTO agente (DNI, EMAIL, TELEFONO, NOMBRE, APELLIDOS, SALARIO_BASE, OBSERVACIONES) 
	VALUES ('41275026C', 'agente@catai.es','901789521','Leonor','Aranguez',2100,'Agente de ventas');
INSERT INTO agente (DNI, EMAIL, TELEFONO, NOMBRE, APELLIDOS, SALARIO_BASE, OBSERVACIONES) 
	VALUES ('06847101D', 'agente@horizonte.es','900112233','Laura','Cruz',1400,'Agente de ventas');

COMMIT;

CREATE TABLE RESERVA (
  ID_RESERVA NUMBER NOT NULL,
  FECHA_RESERVA DATE NOT NULL,
  NUM_DIAS NUMBER NOT NULL,
  IMPORTE_RESERVA NUMBER(8,2) NOT NULL,
  ID_CLIENTE NUMBER NOT NULL,
  ID_PRODUCTO NUMBER NOT NULL,
  DNI_AGENTE VARCHAR2(9),
  CONSTRAINT PK_RESERVA PRIMARY KEY (ID_RESERVA),
  CONSTRAINT FK_RESERVA_ID_CLIENTE FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
  CONSTRAINT FK_RESERVA_ID_PRODUCTO FOREIGN KEY(ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO),
  CONSTRAINT FK_RESERVA_AGENTE FOREIGN KEY(DNI_AGENTE) REFERENCES AGENTE(DNI)
);

COMMENT ON TABLE RESERVA IS 'Datos de las reservas realizadas por un cliente, de un producto, por cada agente';
COMMENT ON COLUMN RESERVA.ID_RESERVA IS 'Identificador de la reserva';
COMMENT ON COLUMN RESERVA.FECHA_RESERVA IS 'Fecha comienzo de la reserva';
COMMENT ON COLUMN RESERVA.NUM_DIAS IS 'Numero de dias de la reserva';
COMMENT ON COLUMN RESERVA.IMPORTE_RESERVA IS 'Importe de la reserva';
COMMENT ON COLUMN RESERVA.ID_CLIENTE IS 'Identificador del cliente que realiza la reserva';
COMMENT ON COLUMN RESERVA.ID_PRODUCTO IS 'Identificador del producto que se reserva';
COMMENT ON COLUMN RESERVA.DNI_AGENTE IS 'Agente a traves del cual se realiza la reserva (solo si no es online)';

CREATE SEQUENCE SEC_RESERVA
INCREMENT BY 1
START WITH 1
MAXVALUE 999999999
NOCACHE
ORDER;

-- Las reservas online no llevan cliente
INSERT INTO RESERVA (ID_RESERVA, FECHA_RESERVA, NUM_DIAS, IMPORTE_RESERVA, ID_CLIENTE, ID_PRODUCTO, DNI_AGENTE) 
	VALUES (SEC_RESERVA.NEXTVAL, '01/05/2020', 2, 150, 1, 1, NULL);
INSERT INTO RESERVA (ID_RESERVA, FECHA_RESERVA, NUM_DIAS, IMPORTE_RESERVA, ID_CLIENTE, ID_PRODUCTO, DNI_AGENTE) 
	VALUES (SEC_RESERVA.NEXTVAL, '01/05/2020', 2, 210, 2, 2, NULL);
INSERT INTO RESERVA (ID_RESERVA, FECHA_RESERVA, NUM_DIAS, IMPORTE_RESERVA, ID_CLIENTE, ID_PRODUCTO, DNI_AGENTE) 
	VALUES (SEC_RESERVA.NEXTVAL, '10/06/2020', 7, 600, 3, 6, NULL);
INSERT INTO RESERVA (ID_RESERVA, FECHA_RESERVA, NUM_DIAS, IMPORTE_RESERVA, ID_CLIENTE, ID_PRODUCTO, DNI_AGENTE) 
	VALUES (SEC_RESERVA.NEXTVAL, '15/07/2020', 7, 1200, 3, 4, '41275026C');

COMMIT;