CREATE TABLE ENTRENADOR (
    ID_ENTRENADOR NUMBER,
    NOMBRE VARCHAR2(25),
    APELLIDOS VARCHAR2(35),
    CONSTRAINT PK_ENTRENADOR PRIMARY KEY (ID_ENTRENADOR)
);

COMMENT ON TABLE ENTRENADOR IS 'Tabla entrenador';
COMMENT ON COLUMN ENTRENADOR.ID_ENTRENADOR IS 'Identificador de la tabla entrenador';
COMMENT ON COLUMN ENTRENADOR.NOMBRE IS 'Campo de la tabla entrenador';
COMMENT ON COLUMN ENTRENADOR.APELLIDOS IS 'Campo de la tabla entrenador';

CREATE TABLE CAMPEONATO (
    ID_CAMPEONATO NUMBER,
    NOMBRE VARCHAR2(35),
    NOMBRE_DEPORTE VARCHAR2(15),
    PAIS VARCHAR(20),
    FECHA_FUND DATE,
    CONSTRAINT PK_CAMPEONATO PRIMARY KEY (ID_CAMPEONATO)
);

COMMENT ON TABLE CAMPEONATO IS 'Tabla Campeonato';
COMMENT ON COLUMN CAMPEONATO.ID_CAMPEONATO IS 'Identificador de la tabla Campeonato';
COMMENT ON COLUMN CAMPEONATO.NOMBRE IS 'Campo de la tabla Campeonato';
COMMENT ON COLUMN CAMPEONATO.NOMBRE_DEPORTE IS 'Campo de la tabla Campeonato';
COMMENT ON COLUMN CAMPEONATO.PAIS IS 'Campo de la tabla Campeonato';
COMMENT ON COLUMN CAMPEONATO.FECHA_FUND IS 'Campo de la tabla Campeonato';



CREATE TABLE EQUIPO (
    CODIGO_EQUIPO VARCHAR2 (10),
    NOMBRE VARCHAR2 (20),
    NOMBRE_ESTADIO VARCHAR2 (15),
    CONSTRAINT PK_EQUIPO PRIMARY KEY (CODIGO_EQUIPO)
);

COMMENT ON TABLE EQUIPO IS 'Tabla Equipo';
COMMENT ON COLUMN EQUIPO.CODIGO_EQUIPO IS 'Identificador de la tabla Equipo';
COMMENT ON COLUMN EQUIPO.NOMBRE IS 'Campo de la tabla Equipo';
COMMENT ON COLUMN EQUIPO.NOMBRE_ESTADIO IS 'Campo de la tabla Equipo';


CREATE TABLE JUGADOR (
    DNI VARCHAR2 (9),
    NOMBRE VARCHAR2 (20),
    EDAD NUMBER,
    SEXO VARCHAR2 (10),
    CODIGO_EQUIPO VARCHAR2 (10),
    CONSTRAINT PK_JUGADOR PRIMARY KEY (DNI),
    CONSTRAINT FK_EQUIPO FOREIGN KEY (CODIGO_EQUIPO) REFERENCES EQUIPO (CODIGO_EQUIPO)
);

COMMENT ON TABLE JUGADOR IS 'Tabla Jugador';
COMMENT ON COLUMN JUGADOR.DNI IS 'Identificador de la tabla Jugador';
COMMENT ON COLUMN JUGADOR.NOMBRE IS 'Campo de la tabla Jugador';
COMMENT ON COLUMN JUGADOR.EDAD IS 'Campo de la tabla Jugador';
COMMENT ON COLUMN JUGADOR.SEXO IS 'Campo de la tabla Jugador';
COMMENT ON COLUMN JUGADOR.CODIGO_EQUIPO IS 'Foreign Key de la tabla Jugador';

CREATE TABLE SELECCION (
    ID_SELECCION NUMBER,
    NOMBRE VARCHAR2(20),
    CATEGORIA VARCHAR2(10),
    NUM_JUGADORES NUMBER,
    DNI VARCHAR2(9),
    CONSTRAINT PK_SELECCION PRIMARY KEY (ID_SELECCION),
    CONSTRAINT FK_JUGADOR FOREIGN KEY (DNI) REFERENCES JUGADOR (DNI)
);

COMMENT ON TABLE SELECCION IS 'Tabla SELECCION';
COMMENT ON COLUMN SELECCION.ID_SELECCION IS 'Identificador de la tabla SELECCION';
COMMENT ON COLUMN SELECCION.CATEGORIA IS 'Campo de la tabla SELECCION';
COMMENT ON COLUMN SELECCION.NUM_JUGADORES IS 'Campo de la tabla SELECCION';
COMMENT ON COLUMN SELECCION.DNI IS 'Foreign Key de la tabla Jugador';

CREATE TABLE CAMPEONATO_SELECCION (
    ID_CAMPEONATO NUMBER,
    ID_SELECCION NUMBER,
    CONSTRAINT FK_CAMPEONATO FOREIGN KEY (ID_CAMPEONATO) REFERENCES CAMPEONATO (ID_CAMPEONATO),
    CONSTRAINT FK_SELECCION FOREIGN KEY (ID_SELECCION) REFERENCES SELECCION (ID_SELECCION)
);

COMMENT ON TABLE CAMPEONATO_SELECCION IS 'Tabla CAMPEONATO_SELECCION';
COMMENT ON COLUMN CAMPEONATO_SELECCION.ID_CAMPEONATO IS 'Foreign Key de la tabla CAMPEONATO_SELECCION';
COMMENT ON COLUMN CAMPEONATO_SELECCION.ID_SELECCION IS 'Foreign Key de la tabla CAMPEONATO_SELECCION';

INSERT INTO EQUIPO (CODIGO_EQUIPO, NOMBRE, NOMBRE_ESTADIO) VALUES ('001', 'Real Madrid', 'Santiago');
INSERT INTO EQUIPO (CODIGO_EQUIPO, NOMBRE, NOMBRE_ESTADIO) VALUES ('002', 'Barcelona', 'Car Nou');
INSERT INTO EQUIPO (CODIGO_EQUIPO, NOMBRE, NOMBRE_ESTADIO) VALUES ('003', 'Betis', 'Balon Pie');
INSERT INTO EQUIPO (CODIGO_EQUIPO, NOMBRE, NOMBRE_ESTADIO) VALUES ('004', 'Sevilla', 'Capital');

COMMIT;

	/*INSERT INTO SELECCION (ID_SELECCION, NOMBRE, CATEGORIA, NUM_JUGADORES, DNI) VALUES (15, 'España', 'Liga BBVA', 11, '05984L');
	INSERT INTO SELECCION (ID_SELECCION, NOMBRE, CATEGORIA, NUM_JUGADORES, DNI) VALUES (16, 'Inglaterra', 'Liga BBVA', 11, '05994L');
	INSERT INTO SELECCION (ID_SELECCION, NOMBRE, CATEGORIA, NUM_JUGADORES, DNI) VALUES (17, 'Croacia', 'Liga BBVA', 11, '05983L');
	INSERT INTO SELECCION (ID_SELECCION, NOMBRE, CATEGORIA, NUM_JUGADORES, DNI) VALUES (18, 'Italia', 'Liga BBVA', 11, '05984M');
	COMMIT;*/

INSERT INTO CAMPEONATO (ID_CAMPEONATO, NOMBRE, NOMBRE_DEPORTE, PAIS, FECHA_FUND) VALUES (13700, 'Champions', 'Futbol 11', 'España', '12-4-2015');
INSERT INTO CAMPEONATO (ID_CAMPEONATO, NOMBRE, NOMBRE_DEPORTE, PAIS, FECHA_FUND) VALUES (13750, 'Champions', 'Futbol 11', 'España', '12-4-2015');
INSERT INTO CAMPEONATO (ID_CAMPEONATO, NOMBRE, NOMBRE_DEPORTE, PAIS, FECHA_FUND) VALUES (13760, 'Champions', 'Futbol 11', 'España', '12-4-2015');
INSERT INTO CAMPEONATO (ID_CAMPEONATO, NOMBRE, NOMBRE_DEPORTE, PAIS, FECHA_FUND) VALUES (13704, 'Europa Leg', 'Futbol 11', 'España', '12-4-2015');
INSERT INTO CAMPEONATO (ID_CAMPEONATO, NOMBRE, NOMBRE_DEPORTE, PAIS, FECHA_FUND) VALUES (13701, 'Europa Leg', 'Futbol 11', 'España', '12-4-2015');

COMMIT;

ALTER TABLE EQUIPO
MODIFY NOMBRE VARCHAR2(25);

ALTER TABLE EQUIPO
MODIFY NOMBRE_ESTADIO VARCHAR2(40);



        DELETE FROM EQUIPO;
        DELETE FROM CAMPEONATO;
        
		COMMIT;

        DROP TABLE CAMPEONATO_SELECCION;
		DROP TABLE SELECCION;
		DROP TABLE JUGADOR;
		DROP TABLE EQUIPO;
		DROP TABLE CAMPEONATO;
        DROP TABLE ENTRENADOR;







