

--Ejercicio 1 ; 

SELECT DES.*
FROM DESARROLLADORES DES
WHERE UPPER (DES.ACTIVO) = 'S'
    AND TO_NUMBER (TO_CHAR(DES.FECHA_FUNDACION, 'YYYY')) > 1950;


--Ejercicio 2 ;

SELECT VJ.TITULO, GEN.NOMBRE, VJ.FECHA_LANZAMIENTO, VJ.PRECIO
FROM VIDEOJUEGOS VJ, GENEROS GEN
WHERE VJ.ID_GENERO = GEN.ID_GENERO
    AND VJ.FECHA_LANZAMIENTO IS NOT NULL;

--Ejercicio 3 ; 

SELECT VJ.*
FROM VIDEOJUEGOS VJ JOIN DESARROLLADORES DES
            ON VJ.ID_DESARROLLADOR = DES.ID_DESARROLLADOR
WHERE DES.ACTIVO = 'S';


--Ejercicio 4 ;

SELECT DES.ID_DESARROLLADOR,
        DES.NOMBRE,
        DES.PAIS,
        DES.FECHA_FUNDACION,
        VJ.TITULO,
        VJ.PRECIO,
        VJ.VENTAS_TOTALES,
        VJ.ID_DESARROLLADOR
FROM DESARROLLADORES DES, VIDEOJUEGOS VJ
WHERE DES.ID_DESARROLLADOR = VJ.ID_DESARROLLADOR 
        AND VJ.VENTAS_TOTALES > 1000000;
        
        
--Ejercicio 5 ;

SELECT PLA.NOMBRE NOMBRE_PLATAFORMA,
        PLA.TIPO,
        DES.NOMBRE NOMBRE_DESARROLLADOR,
        DES.PAIS,
        VJ.TITULO TITULO_VIDEOJUEGO,
        VJ.FECHA_LANZAMIENTO
FROM PLATAFORMAS PLA, DESARROLLADORES DES, VIDEOJUEGOS VJ, VIDEOJUEGOS_PLATAFORMAS VJP
WHERE PLA.ID_PLATAFORMA = PLA.ID_PLATAFORMA
        AND VJP.ID_VIDEOJUEGO = VJ.ID_VIDEOJUEGO
        AND VJ.ID_DESARROLLADOR = DES.ID_DESARROLLADOR
ORDER BY VJ.FECHA_LANZAMINETO DESC;


--Ejercicio 6 ;

SELECT AVG (VJ.PRECIO) AS MEDIA_PRECIO,
        MIN (VJ.PRECIO) AS MINIMO_PRECIO,
        MAX (VJ.PRECIO)AS MAXIMO_PRECIO,
        SUM (VJ.PRECIO) AS TOTAL,
        DES.NOMBRE
FROM DESARROLLADORES DES, VIDEOJUEGOS VJ
WHERE DES.ID_DESARROLLADOR = VJ.ID_DESARROLLADOR
GROUP BY DES.NOMBRE;
        
            
--Ejercicio 7 ;

SELECT VJ.TITULO,
        COUNT(VJP.ID_PLATAFORMA)
FROM VIDEOJUEGOS VJ, PLATAFORMAS PLA, VIDEOJUEGOS_PLATAFORMAS VJP
WHERE VJ.ID_VIDEOJUEGO = VJP.ID_VIDEOJUEGO
        AND PLA.ID_PLATAFORMA = VJP.ID_PLATAFORMA
GROUP BY VJ.TITULO 
HAVING COUNT(VJP.ID_PLATAFORMA) > 1;
    
    
  
  
  
  
________________________________________________________________________


--EJERCICIO Nº 1
SELECT DES.*
FROM DESARROLLADORES DES
WHERE UPPER(DES.ACTIVO) = 'S'
    AND TO_NUMBER(TO_CHAR(DES.FECHA_FUNDACION, 'YYYY')) > '01/01/1950';



--EJERCICIO Nº 2
SELECT VJ.TITULO,
       GEN.NOMBRE,
       VJ.FECHA_LANZAMIENTO,
       VJ.PRECIO
FROM VIDEOJUEGOS VJ, GENEROS GEN
WHERE VJ.ID_GENERO = GEN.ID_GENERO
    AND VJ.FECHA_LANZAMIENTO IS NOT NULL;
 
 
 
--EJERCICIO Nº 3
SELECT VJ.*
FROM VIDEOJUEGOS VJ JOIN DESARROLLADORES DES
                         ON VJ.ID_DESARROLLADOR = DES.ID_DESARROLLADOR
WHERE DES.ACTIVO = 'S';



--EJERCICIO Nº 4
SELECT DES.ID_DESARROLLADOR,
       DES.NOMBRE,
       DES.PAIS,
       DES.FECHA_FUNDACION,
       vj.titulo,
       vj.precio,
       vj.ventas_totales,
       vj.id_desarrollador
FROM DESARROLLADORES DES, VIDEOJUEGOS VJ
WHERE DES.ID_DESARROLLADOR = VJ.ID_DESARROLLADOR 
      AND VJ.VENTAS_TOTALES > 1000000;



--EJERCICIO 5
SELECT pla.nombre NOMBRE_PLATAFORMA,
       pla.tipo,
       des.nombre NOMBRE_DESARROLLADOR,
       des.pais,
       vj.titulo NOMBRE_VIDEOJUEGO,
       vj.fecha_lanzamiento
FROM PLATAFORMAS PLA, DESARROLLADORES DES, VIDEOJUEGOS VJ, VIDEOJUEGOS_PLATAFORMAS VJP
WHERE VJP.ID_PLATAFORMA = PLA.ID_PLATAFORMA
      AND VJP.ID_VIDEOJUEGO = VJ.ID_VIDEOJUEGO
      AND VJ.ID_DESARROLLADOR = DES.ID_DESARROLLADOR
ORDER BY vj.fecha_lanzamiento DESC;



--EJERCICIO Nº 6
SELECT AVG(VJ.PRECIO) AS MEDIA_PRECIO,
       MIN(VJ.PRECIO) AS MINIMO,
       MAX(VJ.PRECIO) AS MAXIMO,
       SUM(VJ.PRECIO) AS TOTAL,
       DES.NOMBRE 
FROM DESARROLLADORES DES, VIDEOJUEGOS VJ
WHERE DES.ID_DESARROLLADOR = VJ.ID_DESARROLLADOR
GROUP BY DES.NOMBRE;



--EJERCICIO Nº 7
SELECT v.titulo, 
     COUNT(vp.id_plataforma) AS num_plataformas
FROM Videojuegos v INNER JOIN Videojuegos_Plataformas vp ON v.id_videojuego = vp.id_videojuego
GROUP BY v.titulo
HAVING COUNT(vp.id_plataforma) > 1
--ORDER BY COUNT(vp.id_plataforma);
ORDER BY num_plataformas;
    
    
    